"""modify the types of attendence

Revision ID: 0994186a090b
Revises: 11f9b3a4b74e
Create Date: 2026-03-23 16:13:22.142817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import update


# revision identifiers, used by Alembic.
revision: str = '0994186a090b'
down_revision: Union[str, Sequence[str], None] = '11f9b3a4b74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

attendance_types = sa.table(
    "attendence_types",
    sa.column("id", sa.Integer),
    sa.column("attendence_type", sa.String),
)

def upgrade() -> None:
    """Upgrade schema."""
    # Reference data is seeded via `python -m app.scripts.seed_initial_data`.
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
