"""add default values

Revision ID: 11f9b3a4b74e
Revises: a0ce1d56b618
Create Date: 2026-03-10 20:28:14.745396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f9b3a4b74e'
down_revision: Union[str, Sequence[str], None] = 'a0ce1d56b618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


attendance_types = sa.table(
    "attendence_types",
    sa.column("id", sa.Integer),
    sa.column("attendence_type", sa.String),
)

payment_types = sa.table(
    "payment_types",
    sa.column("id", sa.Integer),
    sa.column("payment_type", sa.String),
)

salary_types = sa.table(
    "salary_type",
    sa.column("id", sa.Integer),
    sa.column("salary_type", sa.String),
)

vacation_statuses = sa.table(
    "vacation_status",
    sa.column("id", sa.Integer),
    sa.column("vacation_status", sa.String),
)

vacation_types = sa.table(
    "vacation_types",
    sa.column("id", sa.Integer),
    sa.column("vacation_type", sa.String),
)

def upgrade() -> None:
    # Reference data is seeded via `python -m app.scripts.seed_initial_data`.
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
