"""updat the vacation status

Revision ID: 1478fee8bc0a
Revises: 0994186a090b
Create Date: 2026-03-23 16:53:46.901241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1478fee8bc0a'
down_revision: Union[str, Sequence[str], None] = '0994186a090b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

vacation_statuses = sa.table(
    "vacation_status",
    sa.column("id", sa.Integer),
    sa.column("vacation_status", sa.String),
)

def upgrade() -> None:
    """Upgrade schema."""
    # Reference data is seeded via `python -m app.scripts.seed_initial_data`.
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
