"""update the att type of present

Revision ID: 5d86cd3de614
Revises: 1478fee8bc0a
Create Date: 2026-03-23 17:02:37.348085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d86cd3de614'
down_revision: Union[str, Sequence[str], None] = '1478fee8bc0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

attendance_types = sa.table(
    "attendence_types",
    sa.column("id", sa.Integer),
    sa.column("attendence_type", sa.String),
)
def upgrade() -> None:
    """Upgrade schema."""
    # Reference data is seeded via `python -m app.scripts.seed_initial_data`.
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
