"""add annual_vacations table

Revision ID: 98d0d62ed5ea
Revises: 597868aa7989
Create Date: 2026-03-27 16:16:24.883454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d0d62ed5ea'
down_revision: Union[str, Sequence[str], None] = '597868aa7989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.create_table(
        'annual_vacations',
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('allowed_days', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('year', 'employee_id')
    )

    # Use batch_alter_table for SQLite
    with op.batch_alter_table("employees") as batch_op:
        batch_op.alter_column('joined', existing_type=sa.DATE(), nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annual_vacations')
    # ### end Alembic commands ###
