"""initial tables

Revision ID: a0ce1d56b618
Revises: 
Create Date: 2026-03-10 20:24:55.793370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ce1d56b618'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendence_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendence_type', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendence_types_id'), 'attendence_types', ['id'], unique=False)
    op.create_table('payment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_types_id'), 'payment_types', ['id'], unique=False)
    op.create_table('salary_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salary_type', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_type_id'), 'salary_type', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.Time(), nullable=True),
    sa.Column('exit_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_table('vacation_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacation_status', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacation_status_id'), 'vacation_status', ['id'], unique=False)
    op.create_table('vacation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacation_type', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacation_types_id'), 'vacation_types', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('phone', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('dues', sa.DECIMAL(), nullable=False),
    sa.Column('salary_type', sa.Integer(), nullable=False),
    sa.Column('monthly_price', sa.DECIMAL(), nullable=False),
    sa.Column('day_price', sa.DECIMAL(), nullable=False),
    sa.Column('hour_price', sa.DECIMAL(), nullable=False),
    sa.Column('extra_hours_price', sa.DECIMAL(), nullable=False),
    sa.Column('daily_work_hours', sa.Integer(), nullable=False),
    sa.Column('vacation_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allowed_late', sa.DECIMAL(), nullable=False),
    sa.Column('min_extraTime', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['salary_type'], ['salary_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('attendence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.Time(), nullable=False),
    sa.Column('exit_time', sa.Time(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('attendence_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attendence_type'], ['attendence_types.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendence_id'), 'attendence', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('payment_type', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_type'], ['payment_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('vacation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('vacation_type', sa.Integer(), nullable=False),
    sa.Column('vacation_status', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacation_status'], ['vacation_status.id'], ),
    sa.ForeignKeyConstraint(['vacation_type'], ['vacation_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacation_id'), 'vacation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacation_id'), table_name='vacation')
    op.drop_table('vacation')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_attendence_id'), table_name='attendence')
    op.drop_table('attendence')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_vacation_types_id'), table_name='vacation_types')
    op.drop_table('vacation_types')
    op.drop_index(op.f('ix_vacation_status_id'), table_name='vacation_status')
    op.drop_table('vacation_status')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_salary_type_id'), table_name='salary_type')
    op.drop_table('salary_type')
    op.drop_index(op.f('ix_payment_types_id'), table_name='payment_types')
    op.drop_table('payment_types')
    op.drop_index(op.f('ix_attendence_types_id'), table_name='attendence_types')
    op.drop_table('attendence_types')
    # ### end Alembic commands ###
